source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'devise'
gem 'devise-encryptable'
gem 'activeadmin', github: 'gregbell/active_admin'
gem 'bootstrap-sass'
gem 'bootstrap-datepicker-rails'
gem 'simple_form'
gem 'nested_form'
gem 'paperclip'
gem 'country_select'
gem 'openlayers-rails'
gem 'httparty'
gem 'momentjs-rails'
gem 'js-routes'
gem 'kaminari'
gem 'chart-js-rails'
gem 'prawn'
gem 'pdfkit'
gem 'select2-rails'
gem 'axlsx'
gem 'tzinfo-data', platforms: [:mingw, :mswin]
gem 'prawn-table'
gem 'seed_dump'
gem 'pundit'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'rails_config'
gem 'icomoon-rails'
gem 'toastr-rails'
gem 'therubyracer'
